[package]
name = "StickerProcess"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
#ffmpeg-next = "8"
dioxus = { version = "0.7", features = ["desktop"] }
ffmpeg-the-third = "6"
ffmpeg-sidecar = "2.5"
log = "0.4.34"
oxipng = { version = "10.2", features = ["parallel", "zopfli"], default-features = false }
pretty_env_logger = "0.5.0"
rfd = "0.17"
tokio = "1.53"

[profile.release]
opt-level = "s"       # 优化代码尺寸，兼顾速度
lto = "fat"           # 启用最大程度的链接时优化
codegen-units = 1     # 降低代码生成单元数，增加优化时间但提升性能
panic = "abort"       # 使用 'abort' 而不是 'unwind' 来处理 panic
strip = "symbols"     # 移除符号信息，保留必要的调试信息
